# Artificail Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

2022-01-20 11:27:04.478027: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-20 11:27:04.478157: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the Dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding Categorical data

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

### Feature Scaling

In [7]:
# Feature scaling is absolutely necessary for DL

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initialinzing the ANN

In [8]:
ann = tf.keras.models.Sequential()

2022-01-20 11:27:30.625190: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-20 11:27:30.625324: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-20 11:27:30.625426: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Alderson): /proc/driver/nvidia/version does not exist


### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu')) #activation_function used is "rectifier activation function".

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu')) #activation_function used is "rectifier activation function".

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
#param's - loss='binary_crossentropy'-> for binary classification and for non binary classification loss='categorical_crossentropy' and
#then the activation will be =soft_max
ann.compile(optimizer = 'adam', loss='binary_crossentropy', metrics = ['accuracy']) 

### Training the ANN on the Training set

In [13]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 5s 6ms/step - loss: 0.5760 - accuracy: 0.7366
Epoch 2/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4719 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4467 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4357 - accuracy: 0.7962
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4287 - accuracy: 0.7969
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4226 - accuracy: 0.7987
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4169 - accuracy: 0.8011
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4110 - accuracy: 0.8099
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4047 - accuracy: 0.8300
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3986 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

#### Solution

In [14]:
#setting the threshold of .5
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the test set results

In [15]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
a_score = accuracy_score(y_test, y_pred)
print(cm)
print(a_score)

[[1510   85]
 [ 193  212]]
0.861
